/**
 * Figure image download utilities (PNG and SVG).
 *
 * Builds a composite SVG containing title, plot, optional legend, and source
 * attribution, then exports as SVG or renders to Canvas at 2× for PNG.
 */

import { plotSymbolPath } from './plotSymbols';

// --- Types ---

export interface LegendItem {
  color: string;
  label: string;
  symbol?: string;
}

export interface FigureOptions {
  title: string;
  plotSVG: SVGSVGElement;
  legend?: LegendItem[];
  filename: string;
}

export interface MapsFigureOptions {
  title: string;
  /** One entry per grid cell in row-major order. null = blank cell. */
  maps: ({ svg: SVGSVGElement; title: string } | null)[];
  nRows: number;
  nCols: number;
  legendSVGs: SVGSVGElement[];
  filename: string;
}

// --- Constants ---

const NS = 'http://www.w3.org/2000/svg';
const PADDING = 30;
const TITLE_FONT_SIZE = 16;
const TITLE_LINE_HEIGHT = 20;
const SOURCE_FONT_SIZE = 11;
const LEGEND_FONT_SIZE = 12;
const LEGEND_SWATCH_R = 6;
const FONT_FAMILY = 'system-ui, -apple-system, sans-serif';
const SOURCE_TEXT = 'Plot Generated by DCEG NIH-MERGE';

// --- Internal helpers ---

/** Ensure every <text> in the SVG has an explicit font-family so the export is self-contained. */
function inlineFonts(el: Element): void {
  for (const text of el.querySelectorAll('text')) {
    if (!text.getAttribute('font-family')) {
      text.setAttribute('font-family', FONT_FAMILY);
    }
  }
}

/** Trigger a file download from a Blob. */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Build the composite figure SVG. */
function composeFigureSVG(options: FigureOptions): SVGSVGElement {
  const { title, plotSVG, legend } = options;

  // --- Determine content width from the actual plot content bounds ---
  // getBBox() on the live SVG gives the tight bounding box, trimming any
  // dashboard centering margins that pad the SVG to the container width.
  const bbox = plotSVG.getBBox();
  const bboxPad = 5;
  const croppedW = bbox.width + bboxPad * 2;
  const croppedH = bbox.height + bboxPad * 2;
  const contentWidth = Math.max(croppedW, 640);

  let y = PADDING;

  const root = document.createElementNS(NS, 'svg');
  root.setAttribute('xmlns', NS);

  // --- Title (split on " | " into two lines if present) ---
  const titleCenterX = PADDING + contentWidth / 2;
  const titleParts = title.split(' | ');
  const titleGroup = document.createElementNS(NS, 'text');
  titleGroup.setAttribute('font-size', String(TITLE_FONT_SIZE));
  titleGroup.setAttribute('font-weight', 'bold');
  titleGroup.setAttribute('font-family', FONT_FAMILY);
  titleGroup.setAttribute('text-anchor', 'middle');
  titleGroup.setAttribute('x', String(titleCenterX));

  if (titleParts.length > 1) {
    const line1 = document.createElementNS(NS, 'tspan');
    line1.setAttribute('x', String(titleCenterX));
    line1.setAttribute('dy', '0');
    line1.textContent = titleParts[0];
    titleGroup.appendChild(line1);

    const line2 = document.createElementNS(NS, 'tspan');
    line2.setAttribute('x', String(titleCenterX));
    line2.setAttribute('dy', String(TITLE_LINE_HEIGHT));
    line2.textContent = titleParts.slice(1).join(' | ');
    line2.setAttribute('font-size', String(TITLE_FONT_SIZE - 2));
    line2.setAttribute('font-weight', 'normal');
    titleGroup.appendChild(line2);

    titleGroup.setAttribute('y', String(y + TITLE_FONT_SIZE));
    y += TITLE_FONT_SIZE + TITLE_LINE_HEIGHT + 16;
  } else {
    titleGroup.setAttribute('y', String(y + TITLE_FONT_SIZE));
    titleGroup.textContent = title;
    y += TITLE_FONT_SIZE + 16;
  }
  root.appendChild(titleGroup);

  // --- Plot (deep clone, cropped to actual content) ---
  const plotClone = plotSVG.cloneNode(true) as SVGSVGElement;
  plotClone.setAttribute('viewBox',
    `${bbox.x - bboxPad} ${bbox.y - bboxPad} ${croppedW} ${croppedH}`);
  plotClone.style.removeProperty('min-width');
  plotClone.style.removeProperty('flex-grow');
  plotClone.style.removeProperty('flex-shrink');
  inlineFonts(plotClone);

  // Embed as nested <svg> to preserve viewport context for axis label transforms.
  const plotOffsetX = PADDING + Math.max(0, (contentWidth - croppedW) / 2);
  plotClone.setAttribute('x', String(plotOffsetX));
  plotClone.setAttribute('y', String(y));
  plotClone.setAttribute('width', String(croppedW));
  plotClone.setAttribute('height', String(croppedH));
  root.appendChild(plotClone);
  y += croppedH + 12;

  // --- Legend ---
  if (legend && legend.length > 0) {
    const legendGroup = document.createElementNS(NS, 'g');
    let xCursor = 0;

    for (const item of legend) {
      const cx = xCursor + LEGEND_SWATCH_R;

      const symbol = document.createElementNS(NS, 'path');
      symbol.setAttribute('d', plotSymbolPath(item.symbol));
      symbol.setAttribute('fill', item.color);
      symbol.setAttribute('transform', `translate(${cx}, 0)`);
      legendGroup.appendChild(symbol);

      const text = document.createElementNS(NS, 'text');
      text.setAttribute('x', String(cx + LEGEND_SWATCH_R + 4));
      text.setAttribute('y', String(LEGEND_FONT_SIZE * 0.35));
      text.setAttribute('font-size', String(LEGEND_FONT_SIZE));
      text.setAttribute('font-family', FONT_FAMILY);
      text.textContent = item.label;
      legendGroup.appendChild(text);

      xCursor += LEGEND_SWATCH_R * 2 + 4 + item.label.length * 7 + 16;
    }

    const legendWidth = xCursor - 16;
    const legendX = PADDING + (contentWidth - legendWidth) / 2;
    legendGroup.setAttribute('transform', `translate(${Math.max(PADDING, legendX)}, ${y})`);
    root.appendChild(legendGroup);
    y += LEGEND_FONT_SIZE + 16;
  }

  // --- Source text ---
  const sourceEl = document.createElementNS(NS, 'text');
  sourceEl.setAttribute('x', String(PADDING));
  sourceEl.setAttribute('y', String(y + SOURCE_FONT_SIZE));
  sourceEl.setAttribute('font-size', String(SOURCE_FONT_SIZE));
  sourceEl.setAttribute('font-style', 'italic');
  sourceEl.setAttribute('fill', '#666');
  sourceEl.setAttribute('font-family', FONT_FAMILY);
  sourceEl.textContent = SOURCE_TEXT;
  root.appendChild(sourceEl);
  y += SOURCE_FONT_SIZE + PADDING;

  // --- Background (inserted first so it renders behind everything) ---
  const totalWidth = contentWidth + PADDING * 2;
  const totalHeight = y;
  root.setAttribute('width', String(totalWidth));
  root.setAttribute('height', String(totalHeight));
  root.setAttribute('viewBox', `0 0 ${totalWidth} ${totalHeight}`);

  const bg = document.createElementNS(NS, 'rect');
  bg.setAttribute('width', '100%');
  bg.setAttribute('height', '100%');
  bg.setAttribute('fill', 'white');
  root.insertBefore(bg, root.firstChild);

  return root;
}

// --- Public API ---

/** Read figure components from the current DOM. Returns null if no plot SVG exists. */
export function getFigureOptions(filename: string): FigureOptions | null {
  const titleEl = document.getElementById('title');
  const plotEl = document.getElementById('plot');
  const svg = plotEl?.querySelector('svg');
  if (!titleEl || !svg) return null;

  const title = titleEl.textContent ?? '';

  // Extract legend items from the HTML legend (characteristics only)
  const legendEl = document.getElementById('plot-legend')?.querySelector('.epi-legend')
    ?? plotEl?.querySelector('.epi-legend');
  let legend: LegendItem[] | undefined;
  if (legendEl) {
    legend = [];
    for (const item of legendEl.children) {
      const itemEl = item as HTMLElement;
      const swatch = item.querySelector('span:first-child') as HTMLElement | null;
      const label = item.querySelector('span:last-child') as HTMLElement | null;
      const color = itemEl.dataset.legendColor ?? swatch?.style.backgroundColor;
      if (color && label) {
        legend.push({
          color,
          label: label.textContent ?? '',
          symbol: itemEl.dataset.legendSymbol,
        });
      }
    }
  }

  return {
    title,
    plotSVG: svg as SVGSVGElement,
    legend: legend && legend.length > 0 ? legend : undefined,
    filename,
  };
}

/** Download the current figure as an SVG file. */
export function downloadFigureSVG(options: FigureOptions): void {
  const svg = composeFigureSVG(options);
  const svgString = new XMLSerializer().serializeToString(svg);
  downloadBlob(
    new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' }),
    `${options.filename}.svg`,
  );
}

// --- Maps grid figure ---

const MAP_TITLE_FONT_SIZE = 12;
const MAP_GAP = 16;

/** Build a composite SVG for the maps grid layout. */
function composeMapsFigureSVG(options: MapsFigureOptions): SVGSVGElement {
  const { title, maps, nRows, nCols, legendSVGs } = options;

  // Determine per-cell size from the first non-null map's bounding box
  const firstMap = maps.find((m) => m !== null);
  const firstBBox = firstMap?.svg.getBBox();
  const cellW = firstBBox ? firstBBox.width + 10 : 300;
  const cellH = firstBBox ? firstBBox.height + 10 : 200;
  const contentWidth = nCols * cellW + (nCols - 1) * MAP_GAP;

  let y = PADDING;

  const root = document.createElementNS(NS, 'svg');
  root.setAttribute('xmlns', NS);

  // --- Title ---
  const titleCenterX = PADDING + contentWidth / 2;
  const titleGroup = document.createElementNS(NS, 'text');
  titleGroup.setAttribute('font-size', String(TITLE_FONT_SIZE));
  titleGroup.setAttribute('font-weight', 'bold');
  titleGroup.setAttribute('font-family', FONT_FAMILY);
  titleGroup.setAttribute('text-anchor', 'middle');
  titleGroup.setAttribute('x', String(titleCenterX));
  titleGroup.setAttribute('y', String(y + TITLE_FONT_SIZE));
  titleGroup.textContent = title;
  root.appendChild(titleGroup);
  y += TITLE_FONT_SIZE + 16;

  // --- Maps grid ---
  let mapIndex = 0;
  for (let row = 0; row < nRows; row++) {
    for (let col = 0; col < nCols; col++) {
      if (mapIndex >= maps.length) break;
      const entry = maps[mapIndex];
      mapIndex++;

      // Blank cell — leave empty space
      if (!entry) continue;

      const { svg, title: cardTitle } = entry;

      const x = PADDING + col * (cellW + MAP_GAP);
      const cellY = y;

      // Card title
      if (cardTitle) {
        const titleEl = document.createElementNS(NS, 'text');
        titleEl.setAttribute('x', String(x + cellW / 2));
        titleEl.setAttribute('y', String(cellY + MAP_TITLE_FONT_SIZE));
        titleEl.setAttribute('font-size', String(MAP_TITLE_FONT_SIZE));
        titleEl.setAttribute('font-family', FONT_FAMILY);
        titleEl.setAttribute('text-anchor', 'middle');
        titleEl.textContent = cardTitle;
        root.appendChild(titleEl);
      }

      // Map SVG clone
      const bbox = svg.getBBox();
      const bboxPad = 5;
      const clone = svg.cloneNode(true) as SVGSVGElement;
      clone.setAttribute('viewBox',
        `${bbox.x - bboxPad} ${bbox.y - bboxPad} ${bbox.width + bboxPad * 2} ${bbox.height + bboxPad * 2}`);
      clone.setAttribute('x', String(x));
      clone.setAttribute('y', String(cellY + MAP_TITLE_FONT_SIZE + 4));
      clone.setAttribute('width', String(cellW));
      clone.setAttribute('height', String(cellH));
      inlineFonts(clone);
      root.appendChild(clone);
    }
    y += MAP_TITLE_FONT_SIZE + 4 + cellH + MAP_GAP;
  }

  // --- Color legend ---
  if (legendSVGs.length > 0) {
    // Measure total legend width so we can center
    let totalLegendWidth = 0;
    const legendGap = 8;
    const legendClones: SVGSVGElement[] = [];
    for (const lsvg of legendSVGs) {
      const clone = lsvg.cloneNode(true) as SVGSVGElement;
      inlineFonts(clone);
      legendClones.push(clone);
      const w = parseFloat(lsvg.getAttribute('width') || '0') || lsvg.getBoundingClientRect().width || 200;
      totalLegendWidth += w + legendGap;
    }
    totalLegendWidth -= legendGap; // remove trailing gap

    let lx = PADDING + Math.max(0, (contentWidth - totalLegendWidth) / 2);
    for (const clone of legendClones) {
      const w = parseFloat(clone.getAttribute('width') || '200');
      const h = parseFloat(clone.getAttribute('height') || '30');
      clone.setAttribute('x', String(lx));
      clone.setAttribute('y', String(y));
      clone.setAttribute('width', String(w));
      clone.setAttribute('height', String(h));
      root.appendChild(clone);
      lx += w + legendGap;
    }

    // Use the max height of legend SVGs to advance y
    const maxLegendH = Math.max(
      ...legendSVGs.map((s) => parseFloat(s.getAttribute('height') || '0') || s.getBoundingClientRect().height || 30),
    );
    y += maxLegendH + 16;
  }

  // --- Source text ---
  const sourceEl = document.createElementNS(NS, 'text');
  sourceEl.setAttribute('x', String(PADDING));
  sourceEl.setAttribute('y', String(y + SOURCE_FONT_SIZE));
  sourceEl.setAttribute('font-size', String(SOURCE_FONT_SIZE));
  sourceEl.setAttribute('font-style', 'italic');
  sourceEl.setAttribute('fill', '#666');
  sourceEl.setAttribute('font-family', FONT_FAMILY);
  sourceEl.textContent = SOURCE_TEXT;
  root.appendChild(sourceEl);
  y += SOURCE_FONT_SIZE + PADDING;

  // --- Background ---
  const totalWidth = contentWidth + PADDING * 2;
  const totalHeight = y;
  root.setAttribute('width', String(totalWidth));
  root.setAttribute('height', String(totalHeight));
  root.setAttribute('viewBox', `0 0 ${totalWidth} ${totalHeight}`);

  const bg = document.createElementNS(NS, 'rect');
  bg.setAttribute('width', '100%');
  bg.setAttribute('height', '100%');
  bg.setAttribute('fill', 'white');
  root.insertBefore(bg, root.firstChild);

  return root;
}

/** Download the maps figure as an SVG file. */
export function downloadMapsFigureSVG(options: MapsFigureOptions): void {
  const svg = composeMapsFigureSVG(options);
  const svgString = new XMLSerializer().serializeToString(svg);
  downloadBlob(
    new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' }),
    `${options.filename}.svg`,
  );
}

/** Download the maps figure as a PNG file (2× resolution). */
export function downloadMapsFigurePNG(options: MapsFigureOptions): void {
  const svg = composeMapsFigureSVG(options);
  const svgString = new XMLSerializer().serializeToString(svg);

  const width = parseFloat(svg.getAttribute('width')!);
  const height = parseFloat(svg.getAttribute('height')!);
  const scale = 2;

  const canvas = document.createElement('canvas');
  canvas.width = width * scale;
  canvas.height = height * scale;
  const ctx = canvas.getContext('2d')!;
  ctx.scale(scale, scale);

  const img = new Image();
  const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  img.onload = () => {
    ctx.drawImage(img, 0, 0, width, height);
    URL.revokeObjectURL(url);

    canvas.toBlob((blob) => {
      if (!blob) return;
      downloadBlob(blob, `${options.filename}.png`);
    }, 'image/png');
  };

  img.src = url;
}

/** Download the current figure as a PNG file (2× resolution). */
export function downloadFigurePNG(options: FigureOptions): void {
  const svg = composeFigureSVG(options);
  const svgString = new XMLSerializer().serializeToString(svg);

  const width = parseFloat(svg.getAttribute('width')!);
  const height = parseFloat(svg.getAttribute('height')!);
  const scale = 2;

  const canvas = document.createElement('canvas');
  canvas.width = width * scale;
  canvas.height = height * scale;
  const ctx = canvas.getContext('2d')!;
  ctx.scale(scale, scale);

  const img = new Image();
  const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  img.onload = () => {
    ctx.drawImage(img, 0, 0, width, height);
    URL.revokeObjectURL(url);

    canvas.toBlob((blob) => {
      if (!blob) return;
      downloadBlob(blob, `${options.filename}.png`);
    }, 'image/png');
  };

  img.src = url;
}
